apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-expiration-deployment
spec:
  selector:
    matchLabels:
      app: ticketing-expiration
  template:
    metadata:
      labels:
        app: ticketing-expiration
    spec:
      containers:
        - name: ticketing-expiration
          image: muktiarafi/ticketing-expiration-distroless
          ports:
            - containerPort: 8080
              name: http-web
          env:
            - name: REDIS_HOST
              value: ticketing-expiration-redis-service
            - name: PRODUCER_HOST
              value: my-release-kafka-headless
            - name: PRODUCER_PORT
              value: "9092"
            - name: CONSUMER_HOST
              value: my-release-kafka
            - name: CONSUMER_PORT
              value: "9092"