apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-orders-deployment
spec:
  selector:
    matchLabels:
      app: ticketing-orders
  template:
    metadata:
      labels:
        app: ticketing-orders
    spec:
      containers:
        - name: ticketing-orders
          image: muktiarafi/ticketing-orders-distroless
          ports:
            - containerPort: 8080
              name: http-web
          env:
            - name: DB_HOST
              value: ticketing-orders-postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: dbname
                  name: ticketing-orders-container-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: dbuser
                  name: ticketing-orders-container-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: dbpassword
                  name: ticketing-orders-container-secret
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  key: jwtkey
                  name: ticketing-jwt-secret
            - name: PRODUCER_HOST
              value: my-release-kafka-headless
            - name: PRODUCER_PORT
              value: "9092"
            - name: CONSUMER_HOST
              value: my-release-kafka
            - name: CONSUMER_PORT
              value: "9092"