apiVersion: v1
kind: Secret
metadata:
  name: ticketing-payments-container-secret
data:
  dbuser: cG9zdGdyZXMK
  dbpassword: cG9zdGdyZXMK
  dbname: cG9zdGdyZXMK
---
apiVersion: v1
kind: Secret
metadata:
  name: ticketing-payments-postgres-secret
data:
  dbuser: cG9zdGdyZXMK
  dbpassword: cG9zdGdyZXMK
  dbname: cG9zdGdyZXMK