name: ticketing-payments

on:
  push:
    branches:
      - master
    paths:
      - ticketing-payments/**
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: download dependencies
      run: go mod download
      working-directory: ticketing-payments

    - name: Test
      run: go test -v ./...
      working-directory: ticketing-payments
    
    - name: login to dockerhub
      run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
      
    - name: build image
      run: |
        docker build \
        -t muktiarafi/ticketing-payments-distroless:latest \
        -t muktiarafi/ticketing-payments-distroless:$GITHUB_SHA \
        .
      working-directory: ticketing-payments

    - name: push
      run: |
        docker push muktiarafi/ticketing-payments-distroless:latest
        docker push muktiarafi/ticketing-payments-distroless:$GITHUB_SHA
      working-directory: ticketing-payments
