name: ticketing-expiration

on:
  push:
    branches: 
      - master
    paths:
      - ticketing-expiration/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'

      - name: build image
        run: |
          docker build \
          -t muktiarafi/ticketing-expiration-distroless:latest \
          -t muktiarafi/ticketing-expiration-distroless:$GITHUB_SHA \
          .
        working-directory: ticketing-expiration

      - name: push
        run: |
          docker push muktiarafi/ticketing-expiration-distroless:latest
          docker push muktiarafi/ticketing-expiration-distroless:$GITHUB_SHA
        working-directory: ticketing-expiration
